### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by hongyuntw** [SWHL/RapidVideOCR#12]
樓主您好
我裝完環境執行
python main.py的時候出現了以下錯誤

```
Traceback (most recent call last):
  File "C:\Users\hongyun\Desktop\ntucool\RapidVideOCR\rapidocr\text_detect.py", line 24, in <module>
    from .utils_det import (DBPostProcess, check_and_read_gif,
  File "C:\Users\hongyun\Desktop\ntucool\RapidVideOCR\rapidocr\utils_det.py", line 27, in <module>  
    from shapely.geometry import Polygon
  File "C:\ProgramData\Miniconda3\envs\ocr\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\ProgramData\Miniconda3\envs\ocr\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\ProgramData\Miniconda3\envs\ocr\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\ProgramData\Miniconda3\envs\ocr\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\ProgramData\Miniconda3\envs\ocr\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模組。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hongyun\Desktop\ntucool\RapidVideOCR\rapidocr\rapidocr.py", line 16, in <module>
    from .text_detect import TextDetector
  File "C:\Users\hongyun\Desktop\ntucool\RapidVideOCR\rapidocr\text_detect.py", line 28, in <module>
    from utils_det import (DBPostProcess, check_and_read_gif, create_operators,
ModuleNotFoundError: No module named 'utils_det'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\main.py", line 8, in <module>
    from rapidocr import TextDetector, TextSystem
  File "C:\Users\hongyun\Desktop\ntucool\RapidVideOCR\rapidocr\__init__.py", line 5, in <module>
    from .rapidocr import TextSystem, TextDetector
  File "C:\Users\hongyun\Desktop\ntucool\RapidVideOCR\rapidocr\rapidocr.py", line 19, in <module>
    from text_cls import TextDirectionClassifier
ModuleNotFoundError: No module named 'text_cls'
```
是哪邊出問題了呢!?

**Comment by SWHL** [comment]
- 从错误来看，是Shapely库安装有问题，重新安装一下就可以了
- 从这里下载对应你环境对应的[Shapely whl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely)包，然后
```bash
pip install xxxx.whl
```
即可

**Comment by hongyuntw** [comment]
確實 謝謝樓主
我剛剛發現是 pip 安裝 shapely 會有錯
另外的解決方法是用 conda install 
感謝您
