### ISSUE TITLE
找不到指定的模块,好像跟geos有关，请问各位大佬如何解决？ python3.7

### ISSUE THREAD

**Issue by YuChao-SYSU** [SWHL/RapidVideOCR#14]
Traceback (most recent call last):
  File "D:\Programs\RapidVideOCR\rapid_ocr\text_detect.py", line 23, in <module>
    from .utils_det import (DBPostProcess, check_and_read_gif,
  File "D:\Programs\RapidVideOCR\rapid_ocr\utils_det.py", line 27, in <module>
    from shapely.geometry import Polygon
  File "D:\Programs\anaconda3\envs\videocr\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\Programs\anaconda3\envs\videocr\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\Programs\anaconda3\envs\videocr\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\Programs\anaconda3\envs\videocr\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\Programs\anaconda3\envs\videocr\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by SWHL** [comment]
参见 [FAQ](https://github.com/SWHL/RapidVideOCR/blob/main/FAQ.md#q1-%E8%A3%85%E5%AE%8C%E7%8E%AF%E5%A2%83%E4%B9%8B%E5%90%8E%E8%BF%90%E8%A1%8Cpython-mainpy%E4%B9%8B%E5%90%8E%E6%8A%A5%E9%94%99oserror-winerror-126-%E6%89%BE%E4%B8%8D%E5%88%B0%E6%8C%87%E5%AE%9A%E7%9A%84%E6%A8%A1%E7%B5%84)
