### ISSUE TITLE
测试视频没问题，换上自己的视频就报错了，求大佬看看。。Failed to seek_accurate to frame {}".format(pos)

### ISSUE THREAD

**Issue by YuChao-SYSU** [SWHL/RapidVideOCR#15]
(videocr) D:\Programs\RapidVideOCR>python main.py
D:\Programs\anaconda3\envs\videocr\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:56: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  "Available providers: '{}'".format(name, ", ".join(available_provider_names)))
Loading C:\Users\YC-\Downloads\从这次疫情看中国AI产业的落地问题_哔哩哔哩_bilibili 2022-05-23 20_04.mp4
[15:10:35] D:\a\decord\decord\src\video\video_reader.cc:312: Failed to seek file to position: 0
[15:10:35] D:\a\decord\decord\src\video\video_reader.cc:312: Failed to seek file to position: 0
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    ocr_result = extractor(mp4_path, time_start, time_end, batch_size)
  File "D:\Programs\RapidVideOCR\rapid_videocr\rapid_videocr.py", line 41, in __call__
    self.height = int(self.vr[0].shape[0])
  File "D:\Programs\anaconda3\envs\videocr\lib\site-packages\decord\video_reader.py", line 104, in __getitem__
    self.seek_accurate(idx)
  File "D:\Programs\anaconda3\envs\videocr\lib\site-packages\decord\video_reader.py", line 234, in seek_accurate
    raise RuntimeError("Failed to seek_accurate to frame {}".format(pos))
RuntimeError: Failed to seek_accurate to frame 0

**Comment by YuChao-SYSU** [comment]
> * 猜测可能原因是视频路径名称中文
> * 如果还不行的话，可以给我共享一下视频，我这里具体看看也行
> * 可以加入QQ群(706807542)，沟通方便一下

感谢大佬回复，应该是我视频的问题，用chrome插件下载的。
我换别的视频就可以了。
