### ISSUE TITLE
开启叠图识别时报错，TypeError: list indices must be integers or slices, not list

### ISSUE THREAD

**Issue by gold-shadow** [SWHL/RapidVideOCR#22]
Running with concat recognition.
OCR:  34%|████████████████████████████████████████████████████████████████████▌                                                                                                                                  | 10/29 [00:12<00:22,  1.20s/it]
Traceback (most recent call last):
  File "d:\RapidVideOCR-2.1.1\RapidVideOCR-2.1.1\demo.py", line 11, in <module>
    extractor(rgb_dir, save_dir)
  File "d:\RapidVideOCR-2.1.1\RapidVideOCR-2.1.1\rapid_videocr\rapid_videocr.py", line 64, in __call__
    srt_result, txt_result = self.concat_rec(img_list, is_txt_dir)
  File "d:\RapidVideOCR-2.1.1\RapidVideOCR-2.1.1\rapid_videocr\rapid_videocr.py", line 107, in concat_rec
    srt_part, txt_part = self.get_match_results(start_i,
  File "d:\RapidVideOCR-2.1.1\RapidVideOCR-2.1.1\rapid_videocr\rapid_videocr.py", line 153, in get_match_results
    matched_path = img_paths[matched_index]
TypeError: list indices must be integers or slices, not list

直接用的VSF切的RGB图片，单图识别正常

**Comment by SWHL** [comment]
方便发我一下RGB图片吗？我这里复现一下，定位一下问题
邮箱或者qq都可

**Comment by SWHL** [comment]
在v2.1.2中已经修复

**Comment by SWHL** [comment]
issue先关闭了，有问题再开
