### ISSUE TITLE
[Bug] 终端使用，只用识别时，参数错误

### ISSUE THREAD

**Issue by SWHL** [SWHL/RapidVideOCR#48]
#### 使用版本
v1.2.8

#### 复现代码
```bash
rapid_videocr -i /content/RGBImages -s outputs
```

#### 存在问题
在终端模式下使用时，不想使用vsf，只传入img_dir时，会报错误：
```bash
Traceback (most recent call last):
  File "/usr/local/bin/rapid_videocr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/rapid_videocr/main.py", line 299, in main
    raise ValueError(
ValueError: --vsf_exe_path or --video_dir must not be None at the same time.
```

**Comment by SWHL** [comment]
已经在`rapidvideocr>=2.2.9`中修复
