### ISSUE TITLE
似乎video.py没有自动取得字幕高度的样子？

### ISSUE THREAD

**Issue by charure** [SWHL/RapidVideOCR#9]
“

PS F:\RapidVideOCR-main> python main.py
Loading assets/test_video/2.mp4
Auto set the subtitle height....
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    is_dilate=is_dilate)
  File "F:\RapidVideOCR-main\rapid_videocr\api.py", line 20, in get_subtitles
    error_num, output_format, text_det, is_dilate)
  File "F:\RapidVideOCR-main\rapid_videocr\video.py", line 48, in __init__
    self.get_subtitle_height()
  File "F:\RapidVideOCR-main\rapid_videocr\video.py", line 91, in get_subtitle_height
    print(f'The subtitle value: {self.subtitle_height}')
AttributeError: 'Video' object has no attribute 'subtitle_height'

”

**Comment by SWHL** [comment]
- 问题已经修复
